# Generated by Django 5.0.6 on 2024-07-25 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_appuser_is_active_appuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='is_staff',
        ),
    ]
